using System.Collections.Generic;
using System.Text;
using LALR.CC.Schema;

namespace LALR.CC.SourceGenerators;

/// <summary>
/// Emits the <c>IPreprocessor</c> surface for grammars that declare a
/// <c>preprocessor:</c> block in YAML: one interface method per directive plus
/// the wiring helpers (<c>BuildPreprocessor</c> dispatch dictionary,
/// <c>WrapPreprocessor</c> adapter factory) consumers use to slot the
/// preprocessor between the lexer and the parser.
/// </summary>
/// <remarks>
/// The directive token's symbol id is resolved here at compile time (index in
/// <see cref="GrammarSchema.Symbols"/>), so the generated <c>BuildPreprocessor</c>
/// is a literal dictionary — no runtime symbol-name lookup. Mirrors how
/// <c>TablesEmitter</c> already inlines symbol ids and <c>VisitorEmitter</c>
/// inlines action names.
/// </remarks>
internal static class PreprocessorEmitter
{
    /// <summary>
    /// Emit the preprocessor surface, or <c>null</c> when the schema has no
    /// preprocessor block (so the caller skips writing a
    /// <c>&lt;Name&gt;.Preprocessor.g.cs</c>). Skipped silently — the absence
    /// of preprocessor config is the default, not an error.
    /// </summary>
    public static string? Emit(GrammarSchema schema, string namespaceName, string className)
    {
        var pre = schema.Preprocessor;
        if (pre == null || pre.Directives == null || pre.Directives.Count == 0)
        {
            return null;
        }

        // Resolve directive symbol → id once. We keep the original insertion
        // order so the emitted interface methods and dispatch table appear in
        // a stable order across builds (driven by YAML key order, the same
        // ordering YamlDotNet preserves on round-trip).
        var symbolIds = new Dictionary<string, int>(System.StringComparer.Ordinal);
        if (schema.Symbols != null)
        {
            for (var i = 0; i < schema.Symbols.Count; i++)
            {
                symbolIds[schema.Symbols[i]] = i;
            }
        }

        var directives = new List<DirectiveInfo>();
        foreach (var kv in pre.Directives)
        {
            if (string.IsNullOrEmpty(kv.Key) || string.IsNullOrEmpty(kv.Value))
            {
                // Already reported by SchemaValidator (LALR0003); skip so the
                // emitted file compiles even when the schema has known errors.
                continue;
            }
            if (!symbolIds.TryGetValue(kv.Key, out var id))
            {
                continue;
            }
            directives.Add(new DirectiveInfo(kv.Key, id, kv.Value, PascalCase(kv.Value)));
        }
        if (directives.Count == 0)
        {
            return null;
        }

        // Conditional directives — resolved to symbol ids at codegen time so
        // the runtime engine compares ints. -1 means "this role is unbound";
        // ConditionalsBlock.Any indicates whether to emit the BuildConditionals
        // method at all.
        var conditionals = ResolveConditionals(pre.Conditionals, symbolIds);

        var sb = new StringBuilder(2048);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by LALR.CC.SourceGenerators. Do not edit.");
        sb.AppendLine("#nullable disable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using LALR.CC;");
        sb.AppendLine("using LALR.CC.LexicalGrammar;");
        sb.AppendLine();
        sb.Append("namespace ").Append(namespaceName).AppendLine(";");
        sb.AppendLine();
        sb.Append("public static partial class ").Append(className).AppendLine();
        sb.AppendLine("{");

        EmitInterface(sb, directives, conditionals);
        sb.AppendLine();
        EmitBuildPreprocessor(sb, directives);
        if (conditionals.Any)
        {
            sb.AppendLine();
            EmitBuildConditionals(sb, conditionals);
        }
        sb.AppendLine();
        EmitWrapPreprocessor(sb, conditionals);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static ConditionalsBlock ResolveConditionals(
        Dictionary<string, string>? declared,
        Dictionary<string, int> symbolIds)
    {
        var block = new ConditionalsBlock();
        if (declared == null || declared.Count == 0)
        {
            return block;
        }
        foreach (var kv in declared)
        {
            var role = kv.Key;
            var symbol = kv.Value;
            if (string.IsNullOrEmpty(symbol) || !symbolIds.TryGetValue(symbol, out var id))
            {
                continue;
            }
            switch (role)
            {
                case "if": block.IfSymbol = id; break;
                case "ifdef": block.IfDefSymbol = id; break;
                case "ifndef": block.IfNDefSymbol = id; break;
                case "else": block.ElseSymbol = id; break;
                case "elif": block.ElifSymbol = id; break;
                case "elifdef": block.ElifDefSymbol = id; break;
                case "elifndef": block.ElifNDefSymbol = id; break;
                case "endif": block.EndIfSymbol = id; break;
            }
        }
        return block;
    }

    private static void EmitInterface(StringBuilder sb, List<DirectiveInfo> directives, ConditionalsBlock conditionals)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Preprocessor handler surface. One <c>OnX</c> overload per directive declared");
        sb.AppendLine("    /// in the YAML's <c>preprocessor:</c> block, plus <c>Rewrite</c> for optional");
        sb.AppendLine("    /// macro substitution on non-directive tokens. Each <c>OnX</c> receives the");
        sb.AppendLine("    /// directive's same-line arg tokens and returns the tokens to inject in place");
        sb.AppendLine("    /// of the directive line (empty to drop the directive entirely). <c>Rewrite</c>");
        sb.AppendLine("    /// is called for every non-directive token — return <c>new[] { token }</c> for");
        sb.AppendLine("    /// passthrough, or a different token list to substitute (macro expansion).");
        if (conditionals.Any)
        {
            sb.AppendLine("    /// <c>IsDefined</c> resolves a macro name for the conditional engine's");
            sb.AppendLine("    /// <c>#ifdef</c>/<c>#ifndef</c> dispatch.");
        }
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public interface IPreprocessor");
        sb.AppendLine("    {");
        for (var i = 0; i < directives.Count; i++)
        {
            var d = directives[i];
            sb.Append("        /// <summary>Handler for directive '").Append(EscapeXmlContent(d.Symbol)).AppendLine("'.</summary>");
            sb.Append("        IEnumerable<Item> ").Append(d.MethodName).AppendLine("(IReadOnlyList<Item> args);");
        }
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Rewrite a non-directive token. Default-style impl: <c>return new[] { token };</c>.");
        sb.AppendLine("        /// Override to expand identifier-style macros defined via directive handlers.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        IEnumerable<Item> Rewrite(Item token);");
        if (conditionals.Any)
        {
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Return whether <paramref name=\"name\"/> is currently defined as a macro.");
            sb.AppendLine("        /// Called by the conditional engine for <c>#ifdef</c>/<c>#ifndef</c>.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        bool IsDefined(string name);");
        }
        sb.AppendLine("    }");
    }

    private static void EmitBuildPreprocessor(StringBuilder sb, List<DirectiveInfo> directives)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Build the directive-id → handler dictionary the runtime");
        sb.AppendLine("    /// <see cref=\"PreprocessorTokenStream\"/> consumes. Symbol ids are inlined here at");
        sb.AppendLine("    /// codegen time — no runtime symbol-name lookup.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IReadOnlyDictionary<int, Func<IReadOnlyList<Item>, IEnumerable<Item>>> BuildPreprocessor(IPreprocessor impl)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(impl);");
        sb.AppendLine("        return new Dictionary<int, Func<IReadOnlyList<Item>, IEnumerable<Item>>>()");
        sb.AppendLine("        {");
        // Trailing comment per row carries the directive's source symbol — keeps
        // the generated file legible when reading what each id maps to.
        for (var i = 0; i < directives.Count; i++)
        {
            var d = directives[i];
            sb.Append("            [").Append(d.SymbolId)
              .Append("] = args => impl.").Append(d.MethodName)
              .Append("(args), // ").AppendLine(EscapeCommentContent(d.Symbol));
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static void EmitBuildConditionals(StringBuilder sb, ConditionalsBlock conditionals)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Build the <see cref=\"PreprocessorConditionals\"/> struct the runtime");
        sb.AppendLine("    /// <see cref=\"PreprocessorTokenStream\"/> consumes for the conditional");
        sb.AppendLine("    /// engine. Role-to-symbol-id bindings come from the YAML's");
        sb.AppendLine("    /// <c>preprocessor.conditionals</c> block; unbound roles are inlined as -1.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static PreprocessorConditionals BuildConditionals(IPreprocessor impl)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(impl);");
        sb.Append("        return new PreprocessorConditionals(");
        sb.Append("ifSymbol: ").Append(conditionals.IfSymbol).Append(", ");
        sb.Append("ifDefSymbol: ").Append(conditionals.IfDefSymbol).Append(", ");
        sb.Append("ifNDefSymbol: ").Append(conditionals.IfNDefSymbol).Append(", ");
        sb.Append("elseSymbol: ").Append(conditionals.ElseSymbol).Append(", ");
        sb.Append("endIfSymbol: ").Append(conditionals.EndIfSymbol).AppendLine(",");
        sb.Append("            isDefined: impl.IsDefined,");
        sb.Append(" elifSymbol: ").Append(conditionals.ElifSymbol).Append(",");
        sb.Append(" elifDefSymbol: ").Append(conditionals.ElifDefSymbol).Append(",");
        sb.Append(" elifNDefSymbol: ").Append(conditionals.ElifNDefSymbol).AppendLine(");");
        sb.AppendLine("    }");
    }

    private static void EmitWrapPreprocessor(StringBuilder sb, ConditionalsBlock conditionals)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// One-call helper: wrap <paramref name=\"inner\"/> in a");
        sb.AppendLine("    /// <see cref=\"PreprocessorTokenStream\"/> driven by <paramref name=\"impl\"/>'s");
        sb.AppendLine("    /// directives and <c>Rewrite</c> hook. Pipeline shape:");
        sb.AppendLine("    /// <c>BytesLexer → WrapPreprocessor → SyncLATokenIterator → Parser</c>.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static PreprocessorTokenStream WrapPreprocessor(ISyncIterator<Item> inner, IPreprocessor impl)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(inner);");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(impl);");
        if (conditionals.Any)
        {
            sb.AppendLine("        return new PreprocessorTokenStream(inner, BuildPreprocessor(impl), impl.Rewrite, BuildConditionals(impl));");
        }
        else
        {
            sb.AppendLine("        return new PreprocessorTokenStream(inner, BuildPreprocessor(impl), impl.Rewrite);");
        }
        sb.AppendLine("    }");
    }

    /// <summary>
    /// Conditional-directive role resolution: each well-known role (if /
    /// ifdef / ifndef / else / elif / elifdef / elifndef / endif) gets a
    /// symbol id resolved at codegen time. <c>-1</c> means the YAML didn't bind that role. <see cref="Any"/>
    /// is true when at least one role is bound — drives whether the
    /// generator emits the IsDefined interface method, BuildConditionals
    /// helper, and the conditional-aware WrapPreprocessor call.
    /// </summary>
    private sealed class ConditionalsBlock
    {
        public int IfSymbol { get; set; } = -1;
        public int IfDefSymbol { get; set; } = -1;
        public int IfNDefSymbol { get; set; } = -1;
        public int ElseSymbol { get; set; } = -1;
        public int ElifSymbol { get; set; } = -1;
        public int ElifDefSymbol { get; set; } = -1;
        public int ElifNDefSymbol { get; set; } = -1;
        public int EndIfSymbol { get; set; } = -1;
        public bool Any => IfSymbol >= 0 || IfDefSymbol >= 0 || IfNDefSymbol >= 0
            || ElseSymbol >= 0 || ElifSymbol >= 0 || ElifDefSymbol >= 0
            || ElifNDefSymbol >= 0 || EndIfSymbol >= 0;
    }

    private readonly struct DirectiveInfo
    {
        public DirectiveInfo(string symbol, int symbolId, string actionName, string methodName)
        {
            Symbol = symbol;
            SymbolId = symbolId;
            ActionName = actionName;
            MethodName = methodName;
        }
        public string Symbol { get; }
        public int SymbolId { get; }
        public string ActionName { get; }
        public string MethodName { get; }
    }

    private static string PascalCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }
        if (char.IsUpper(name[0]))
        {
            return name;
        }
        return char.ToUpperInvariant(name[0]) + name.Substring(1);
    }

    /// <summary>
    /// Escape a string for inclusion in an XML doc comment (the <c>///</c>
    /// lines). Directive symbol could contain angle brackets / ampersands —
    /// keep the doc comment well-formed regardless.
    /// </summary>
    private static string EscapeXmlContent(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return value;
        }
        var sb = new StringBuilder(value.Length);
        foreach (var c in value)
        {
            switch (c)
            {
                case '<': sb.Append("&lt;"); break;
                case '>': sb.Append("&gt;"); break;
                case '&': sb.Append("&amp;"); break;
                default: sb.Append(c); break;
            }
        }
        return sb.ToString();
    }

    /// <summary>
    /// Strip CR/LF for inclusion in a trailing single-line <c>//</c> comment.
    /// Other characters pass through unchanged.
    /// </summary>
    private static string EscapeCommentContent(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return value;
        }
        if (value.IndexOfAny(['\r', '\n']) < 0)
        {
            return value;
        }
        var sb = new StringBuilder(value.Length);
        foreach (var c in value)
        {
            if (c != '\r' && c != '\n')
            {
                sb.Append(c);
            }
        }
        return sb.ToString();
    }
}
